# Generated by Django 4.2.5 on 2023-09-10 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3D', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claseProducto', models.CharField(max_length=40)),
                ('nombreProducto', models.CharField(max_length=40)),
            ],
        ),
    ]
