# Generated by Django 4.2.5 on 2023-09-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3D', '0003_pedidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='Stock',
            field=models.IntegerField(default=0),
        ),
    ]
