# Generated by Django 4.2.5 on 2023-09-12 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3D', '0005_rename_filamento_pedidos_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
